quattor/quattor.github.com

_posts/2015-03-03-grenoble-workshop-summary.md

Obivously not ready for merging yet!

Grenoble workshop summary

---

contacts/index.md

* We are friendly people, we should appear that way.
* We don't use Twitter, so drop it.
* We rarely use Google+ so be up front about that.
* We have more than one mailing list.

Overhaul contacts page

---

_includes/menu.html

Tidy navbar

---

_posts/2015-03-03-grenoble-workshop-summary.md

We missed during the original review that the text was not displayed properly on Jekyll due to missing blank lines...

Grenoble summary: fix formatting errors

---

_includes/docmenu.md
_posts/2015-03-25-SCDB-installation.md

Work in progress. Reviewed until `Quattor Server` heading.
Fixes #129.

Migrate SCDB installation doc from LAL wiki

---

_posts/2015-06-03-announcing-quattor-15.4.0.md

Announce Quattor 15.4.0

---

.gitignore
.travis.yml
Gemfile
_config.yml
travis-build

Based on guide at http://jekyllrb.com/docs/continuous-integration/

Test page builds with travis-ci

---

_layouts/article.html
documentation/other.html

Remove disqus comments and supporting logic

---

_includes/footer.html

This way no-one has to remember to update the copyright message each year.

Generate the current year when pages are rebuilt

---

Gemfile
_config.yml
_includes/head.html

Produce an atom feed of posts

---

_posts/2016-01-11-announcing-quattor-15.12.0.md

Add known issue for cdispd

---

_posts/2016-02-19-announcing-quattor-16.2.0.md

Announce 16.2.0

---

_posts/2015-10-29-announcing-quattor-15.8.0.md
_posts/2016-01-11-announcing-quattor-15.12.0.md
_posts/2016-02-19-announcing-quattor-16.2.0.md

Explicitly list backwards incompatible changes

---

_posts/2016-03-08-development-basics.md

Munge link into something renderable

---

contacts/index.md

Makes sense to have this information on the site. Resolves #158

Include info about meetings on Contacts page

---

meeting/index.md

Explain what standups and workshops are.

Add some context to the meetings index page

---

_posts/2016-09-15-announcing-quattor-16.8.0.md

Announce 16.8.0

---

_posts/2012-10-31-install-aquilon.md

Some small changes in the installation procedure.

Minor aquilon doc update

---

_posts/2016-07-29-choice-type.md

Documentation regarding https://github.com/quattor/pan/pull/121 in the pan repository.

Documentation about the implementation of the choice-type

---

_posts/2008-08-21-panc-release-candidate-v814-available.md
_posts/2008-11-03-6th-quattor-workshop-takes-place-in-amsterdam.md
_posts/2008-11-06-quattor-14-is-out.md
_posts/2008-11-24-quattor-usenix-lisa08.md
_posts/2009-02-07-panc-826-has-been-released.md
_posts/2009-02-15-panc-826-has-been-released.md
_posts/2009-02-27-slides-posted-from-recent-tutorial.md
_posts/2009-03-09-7th-workshop-london-11-13-march.md
_posts/2009-04-18-panc-828-has-been-released.md

Copy news items from old quattor sourceforge into current format

---

_posts/2017-01-04-announcing-quattor-16.12.0.md

Add release notes for 16.12.0 to the news category.

Announce 16.12.0 release

---

_posts/2016-10-04-london-workshop.md

This is my (raw) notes from the workshop... You are better to review them before publishing! 
BTW, due to my position in the room, I had difficulties to follow discussions the first day and you may want to add missing bits. Hopefully, I captured the most important things...
Feel free to open a pull request against my source branch with your mods: it may be easier...

Add London workshop summary

---

contacts/index.md

Based on some feedback and experiences here.
More buttons... people like buttons.

Update contacts page to improve clarity

---

_posts/2013-10-01-documentation-getting-started.md

Referring to the actual installation page

Link to the Install instruction

---

_posts/2017-03-21-annecy-workshop.md

This PR requires #213 for the tests to pass (due to the need to exclude SonarQube url used in the summary).

Annecy workshop summary added

---

.gitignore
_aquilon/00-install.md
_aquilon/site_configuration.md
_posts/2009-11-04-workshop.md

- Installation guide replaced by a reference to Aquilon `README.md` file (until the README content is moved back to the web site...)
- Configuration steps updated/clarified based on March 17 workshop hands-on session

Aquilon documentation update

---

_posts/2009-03-11-workshop.md
_posts/2017-02-27-uefi-support.md
github-beginners.md

Documentation on UEFI support in AII. To be merged after https://github.com/quattor/aii/pull/225 has been merged..

Add documentation on UEFI support in AII

---

_posts/2014-02-26-cheat-sheet.md

Bring example Pan snippets up to date with current coding practices.

Modernise cheat sheet

---

_aquilon/00-install.md

Replaces https://github.com/quattor/aquilon/pull/63

aquilon: instruction to setup gerrit commit hook when contributing

---

_posts/2017-06-15-announcing-quattor-17.3.0.md

i.e. quattor/configuration-modules-core#1141

Warn against use of 17.3 due to altlogrotate bug

---

_aquilon/00-install.md

Add `trash_branch` setup instructions.
Resolves quattor/aquilon#60

Expand Git Configuration section in Installing Aquilon docs

---

documentation/index.md

* Add documentation links for two latest releases.
* Add link to Pan documentation.

Add missing links to documentation

---

.travis-scripts/dictionary.txt
downloads/index.md

Current release managers, release cycles etc.

Update information on downloads page to new reality

---

_config.yml
_development/00-basics.md
_development/unittests.md
_includes/link_definitions.md
_other/SCDB-usage.md
_posts/2011-10-11-workshop.md
_posts/2018-04-11-new-quattor-list.md
contacts/index.md
news/index.md

- Add a news related to the list change
- Add an include file to define link reference

 Update Quattor list name

---

quattor.css

Fix mixed content warnings from browsers when viewing https://www.quattor.org.

Fix mixed content warnings

---

.travis-scripts/spellchecker

spellchecker script: fix check of TRAVIS_COMMIT_RANGE variable

---

.travis-scripts/dictionary.txt
_aquilon/technical_details.md
_includes/link_definitions.md
_posts/2006-03-22-workshop.md

Clusters, metaclusters, services added.
Also includes a dictionary cleanup after a spellcheck fix.

Aquilon concepts: a few additions

---

.travis-scripts/dictionary.txt
_aquilon/00-install.md
_aquilon/management.md
_includes/link_definitions.md

- Include a section in install documentation about NFS-based sandboxes

Aquilon doc: improve documentation on user and sandbox management

---

_posts/2018-07-30-quattor-18.6.0.md

Add the auto-generated release notes for 18.6.0.

Announce 18.6.0

---

.travis-scripts/dictionary.txt
_config.yml
_includes/docmenu.md
_initial_installation/uefi-support.md

- Move "hidden" post on UEFI support to the new submenu

Doc menu: create an AII-related submenu

---

.tests/dictionary.txt
_development/coding_style.md

Update Perl coding style
