quattor/quattor.github.com

- Gemfile
This should ensure that the travis build environment matches the page build environment.
> Add github-pages to Gemfile

- documentation/index.md
Adds the link for the 16.2.0 documentation. 
It has:
- configuration-modules-core documentation
- configuration-modules-grid schema's
- CAF
- CCM
For next release I would like a better index and add configuration-modules-grid.
> add link to 16.2.0 documentation

- _includes/docmenu.md
Add a menu to easily locate the most important documentation for developers.
> Add a 'Development' category to docmenu

- _includes/menu.html
The information on the historical wiki is now mostly obsolete, better no to point users to it!
> Remove 'Historical Wiki' from menu

- documentation/index.md
needs https://github.com/quattor/documentation/pull/2 merged and built in readthedocs.
> link to 16.6.0 documentation

- .travis.yml
- _includes/head.html
- _posts/2009-03-11-workshop.md
Newer versions of activesupport now require ruby 2.2 or newer.
Github pages is using ruby 2.3.1.
> Fixes for travis builds

- _posts/2006-03-22-workshop.md
Page hasn't been reachable since 2007, but might be of historical interest (maybe), so at least provide an archived copy.
> Replace dead link with last web archive copy

- documentation/index.md
requires https://github.com/quattor/documentation/pull/6 to be merged and tagged.
> add a link to the 16.10 docs

- _posts/2016-10-04-london-workshop.md
The October 2016 London Workshop summary was in the 'News' category
whereas all previous workshop summaries have the category of 'meeting'.
> Change category of London Workshop to Meeting

- .travis-scripts/html-proofer
- .travis-scripts/url-ignore
- .travis.yml
- travis-build
This PR moves the `travis-script` script in `.travis-scripts/html-proofer`  and adds a list of URL to exclude in the checks maintained as a separate file (rather than an inline list of url patterns in the script).
> Add a file to declare URL to ignore in html-proofer tests

- .travis.yml
- _config.yml
The `gems` option has been renamed to `plugins` - update our config to reflect this and remove the warning message on builds.
Cache html-proofer files - this should result in faster builds that throw fewer spurious http errors.
> Update Jekyll and Travis configuration

- .travis-scripts/spellchecker
- .travis.yml
Update environment to allow spellchecker to run
* Switch to Trusty based containers
* Install enchant library
* Set Python 3.5 with pyenv
* Install pyenchant module against Python 3.5
Fixes #229.
> travis: Update environment to allow spellchecker to run

- .travis-scripts/spellchecker
- .travis.yml
- Gemfile
- _layouts/home.html
Travis has updated to images based on Ubuntu's Trusty release and moved quite a few things around in the process, we've also let our versions drift behind [what GitHub is using to build pages](https://pages.github.com/versions/) which has caused build breakage.
> TravisCI: Fix build environment

- .travis-scripts/dictionary.txt
- .travis-scripts/spellchecker
- documentation/index.md
> Link to Pan cheatsheet from documentation index.

- _layouts/home.html
There is an archived version of the page at https://web.archive.org/web/20170206145904/http://www.wallstreetandtech.com:80/infrastructure/morgan-stanley-growing-its-use-of-linux/d/d-id/1261644, but it doesn't seem worth preserving the link.
> Remove dead link to WallStreetTech

- .travis-scripts/dictionary.txt
- _aquilon/00-install.md
- _aquilon/configuration.md
- _aquilon/management.md
- _aquilon/zz-contributing.md
- _includes/link_definitions.md
- _layouts/article.html
- Configuration: add a section on how to do the actual configuration of a host with the template library
- Includes typical content for the main site templates needed
- Configuration tutorial reviewed and fixed after an actual execution!
- Spelling mistakes fixed
**Final content must be adjusted after #87 has been finalized**
> Aquilon documentation improvements

- .travis-scripts/spellchecker
This adds support for ignoring of liquid tags and HTML entities.
> Update markdown-spellchecker to version 1.4

- _aquilon/configuration.md
* `archetype/final.pan`: add missing Quattor client configuration
* `archetype/base.pan`: add a file system configuration example
> Aquilon initial configuration: fix template examples

- .travis-scripts/spellchecker
Fix typo spotted by https://github.com/stdweird/quattor.github.com/pull/2#discussion_r204661930 after the merge of #253.
> spellchecker script: fix typo

- .travis-scripts/dictionary.txt
- _aquilon/00-install.md
- _aquilon/configuration.md
* Miscellaneous changes in the template examples, based on LAL experience
* Document AII installack configuration for Aquilon, in particular when sharing an AII server between SCDB and Aquilon
> Aquilon installation: various refinements

- _posts/2015-09-22-textrender-outside-metaconfig.md
Move in a separate PR a problem originally fixed as part of #259 but independent of it and affecting any new PR for the web site.
> Fix a wrong link to Quattor ReadTheDocs in an old post

- documentation/index.md
These are more necessary as we switch doc build systems, which causes the RtD version selector to behave oddly.
> Add direct links to 17.12 and 18.6 docs

- .travis-scripts/html-proofer
- _development/00-basics.md
- _development/unittests.md
As suggested in https://github.com/quattor/configuration-modules-core/pull/1464
Please have a look @ned21
> Add information on running tests with docker/podman

- .travis-scripts/html-proofer
Too many false errors causing builds to fail incorrectly.
Fixes #270
> Travis config: disable all external URL checks

- Gemfile
As noted in #277 this appears to cause GitHub Pages to throw a warning.
> Remove Ruby version requirement

- _development/coding_style.md
See also https://github.com/quattor/CAF/issues/109
> coding_style: Document each's evilness
